La_Cripta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name='inicio'),
    path('colección/', include('colección.urls')),
    path('usuarios/', include('usuarios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

colección/urls.py
from django.urls import path
from . import views

app_name = 'colección'
urlpatterns = [
    path('', views.listar, name='listar'),
    path('<letra>', views.listar, name='listar'),
    path('crear/', views.crear, name='crear' ),
    path('detallar/<int:id>', views.detallar, name='detallar'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('borrar/<int:id>', views.borrar, name='borrar'),
    path('borrar/<int:id>/confirmar/', views.borrar_confirm, name='borrar_confirm'),
]

usuarios/urls.py
from django.urls import path
from . import views 

app_name = 'usuarios'
urlpatterns = [
    path('', views.listar, name='listar'),
    path('<letra>', views.listar, name='listar'),
    path('crear/', views.crear, name='crear'),
    path('detallar/<int:id>', views.detallar, name='detallar'),
    path('buscar_libros/', views.buscar_libros, name='buscar_libros'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('confirmacion-borrar/<int:id>', views.confirmacionBorrar, name='confirmacion-borrar'),
    path('borrar/<int:id>', views.borrar, name='borrar'),
    path('borrarYDevolverLibro/<int:id>', views.borrarYDevolverLibro, name='borrarYDevolverLibro'), #
    path('devolver/<int:id>', views.devolver, name='devolver'),

]

colección/models.py
from django.db import models
from django.utils import timezone



class Colección(models.Model):
    titulo = models.CharField(max_length=100, blank=False, null=False)
    autor = models.CharField(max_length=100, blank=False, null=False)
    fecha_de_publicacion = models.DateField(blank=True, null=True)
    editorial = models.CharField(max_length=100, blank=True, null=True)
    resumen = models.TextField(max_length=1000, blank=True, null=True) 
    GENERO_CHOICES = (
    ('Ciencia Ficción', 'Ciencia Ficción'),
    ('Romance', 'Romance'),
    ('Misterio', 'Misterio'),
    ('Fantasía', 'Fantasía'),
    ('Aventura', 'Aventura'),
    ('Drama', 'Drama'),
    ('Terror', 'Terror'),
    ('Biografía', 'Biografía'),
    ('Autoayuda', 'Autoayuda'),
    ('Histórico', 'Histórico'),
    ('Infantil', 'Infantil'),
    )
    genero = models.CharField(max_length=200, choices=GENERO_CHOICES, blank=False, null=False)
    portada = models.ImageField(upload_to='portadas/', blank=True, null=True)
    IDIOMA_CHOICES = (
    ('Español', 'Español'),
    ('Ingles', 'Ingles'),
    ('Italiano', 'Misterio'),
    ('Braille', 'Braille'),
    ('Latín', 'Latín'),
    ('Alemán', 'Alemán'),
    ('Francés', 'Francés'),
    ('Portugués', 'Portugués'),
    ('Chino', 'Chino'),
    ('Japonés', 'Japonés'),
    ('Ruso', 'Ruso'),
    ('Árabe', 'Árabe'),
    )
    idioma = models.CharField(max_length=100,choices= IDIOMA_CHOICES, blank=False, null=False)
    numero_de_paginas = models.PositiveIntegerField(blank=True, null=True)
    disponible = models.BooleanField(default=True)
    fecha_de_entrada = models.DateField(default = timezone.now)

    def __str__(self):
        return self.titulo

colección/forms.py
from django import forms
from django.forms import ModelForm
from .models import Colección

class Colección_form(ModelForm):
    class Meta:
        model = Colección
        exclude = ('fecha_de_entrada',)
        widgets = {
            'fecha_de_publicacion': forms.DateInput(attrs={'type': 'date'})
        }
    class Media:
        enctype = 'multipart/form-data'

   

colección/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse

from .forms import Colección_form
from .models import Colección
from usuarios.models import Prestamos



def listar(request, letra = None):
    if letra != None:
        colección = Colección.objects.filter(titulo__istartswith = letra)
    else:
        colección = Colección.objects.filter(titulo__contains = request.GET.get('search', ''))

    contexto = {
        'colección' : colección
    } 

    return render(request, 'colección/view.html', contexto)


def crear(request):
    if request.method == 'POST':
        form = Colección_form(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('colección:listar') #revisar porque no anda redirect
    else:
        form = Colección_form()
        
    contexto = {
        'form' : form
    } 
    return render(request, 'colección/create.html', contexto)


def detallar(request, id):
    libro = Colección.objects.get(id=id)

    #si el libro no esta disponible, consulto a quien fue prestado
    '''prestamos = Prestamos.objects.filter(devuelto=False)
    for prestamo in prestamos:
        if prestamo.libros.filter(titulo=libro.titulo):
            libroPrestadoA = f'{prestamo.usuario.nombre}, {prestamo.usuario.apellido}'
            break # esto si ese libro es unico en la biblioteca
        else:
            libroPrestadoA = None'''
    #aca utilizo first() para simplificar el codigo:
    prestamo = Prestamos.objects.filter(devuelto=False, libros__titulo=libro.titulo).first()
    prestadoA = f'{prestamo.usuario.nombre}, {prestamo.usuario.apellido}' if prestamo else None

    contexto = {
        'libro' : libro,
        'prestadoA': prestadoA
    }
    return render(request, 'colección/detail.html', contexto)


def editar(request, id):
    libro = Colección.objects.get(id=id)
    if request.method == 'POST':
        form = Colección_form(request.POST, request.FILES, instance=libro)
        if form.is_valid():
            form.save()
            return redirect('colección:listar')
    else:
        form = Colección_form(instance=libro)
    
    contexto = {
        'form':form,
        'id':id
    }
    return render(request, 'colección/edit.html', contexto)


def borrar_confirm(request, id):
    libro = get_object_or_404(Colección, id=id)
    contexto = {'libro': libro}
    return render(request, 'colección/delete_confirm.html', contexto)


def borrar(request, id):
    if request.method == 'POST':
        libro = Colección.objects.get(id=id)
        libro.delete()
        return redirect('colección:listar')
    else:
        return redirect('colección:borrar_confirm', id=id)
    

colección/templates/colección/create.html
{% extends "layout/base.html" %}

{% block 'title' %}Registrar libro{% endblock 'title' %}


{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock styles %}



{% block 'content' %}

    {% load crispy_forms_tags %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="alert-success"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    

    <form action="{% url "colección:crear" %}" enctype="multipart/form-data" method='POST' novalidate >
        {% csrf_token %}

        {{ form | crispy }}

        <div class = 'd-grid gap-2'>
            <input type="submit" value='Guardar' class= 'btn btn-success'>
            <input type="reset" value='Limpiar' class= 'btn btn-secondary'>
        </div>
    </form>
{% endblock 'content' %}

colección/templates/colección/delete_confirm.html
{% extends "layout/base.html" %}

{% block 'title' %}Confirmar eliminación{% endblock 'title' %}

{% block 'content' %}

    <div class="card">
        <h5 class="card-header text-center">Confirmar eliminación</h5>
        <div class="card-body">
          <h5 class="card-title text-center">¿Estás seguro de que deseas eliminar este libro?</h5>
          <p class="card-text text-center">Libro: {{ libro.titulo }}</p>
            <div class='d-flex justify-content-center'>
                <form method="post" action="{% url 'colección:borrar' id=libro.id %}">
                    {% csrf_token %}
                    <button class="btn btn-warning mx-2 my-3" type="submit">Sí, eliminar</button>
                </form>
                <a class="btn btn-warning mx-2 my-3" href="{% url 'colección:listar' %}">Cancelar</a>
            </div>
               
        </div>
      </div>

{% endblock 'content' %}

colección/templates/colección/detail.html
{% extends "layout/base.html" %}

{% block 'title' %}Libro: nombre del libro{% endblock 'title' %}

{% block 'content' %}

    <div class="card mb-3" style="max-width: 700px;">
        <div class="row g-0">
          <div class="col-md-4">
            {% if libro.portada %}
                <img src="{{libro.portada.url}}" class="img-fluid rounded-start" alt="..." >
            {% endif %}
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{libro.titulo}}</h5>
              <p class="card-text"><b>Autor: &nbsp;</b>{{libro.autor}}</p>
              <p class="card-text"><b>Publicado en: &nbsp;</b>{{libro.fecha_de_publicacion}}</p>
              <p class="card-text"><b>Genero literario: &nbsp;</b>{{libro.genero}}</p>
              <p class="card-text"><b>Idioma: &nbsp;</b>{{libro.idioma}}</p>
              <p class="card-text"><b>Cantidad de paginas: &nbsp;</b>{{libro.numero_de_paginas}}</p>
              <p class="card-text"><b>Fecha de ingreso: &nbsp;</b>{{libro.fecha_de_entrada}}</p>
              <p class="card-text"><b>Disponible: &nbsp;</b>{% if libro.disponible %}Si{% else %}
                No  &nbsp;
            
                <a data-bs-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">+</a>
                  
                <div class="row">
                  <div class="col">
                    <div class="collapse multi-collapse" id="multiCollapseExample1">
                      <div class="card card-body">
                        Prestado a {{prestadoA}}
                      </div>
                    </div>
                  </div>
                </div>
                {% endif %}</p>
              
            </div>
          </div>
          <div class='px-2'>
            <p class="card-text"><small class="text-muted">{{libro.resumen}}</small></p>
          </div>
        </div>
    </div>



    
{% endblock 'content' %}

colección/templates/colección/edit.html
{% extends "layout/base.html" %}

{% block 'title' %}Editar libro{% endblock 'title' %}


{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock styles %}



{% block 'content' %}

    {% load crispy_forms_tags %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="alert-success"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}


    <form action="{% url "colección:editar" id=id %}" enctype="multipart/form-data" method='POST' novalidate>
        {% csrf_token %}
        
        {{ form | crispy }}
        
        <input type="submit" value='guardar' class= 'btn-guardar'>
    </form>
{% endblock 'content' %}

colección/templates/colección/view.html
{% extends "layout/base.html" %}

{% block 'title' %}Colección{% endblock 'title' %}

{% block 'content' %}
{% load static %}

    {% include "colección/partials/by_initial.html" %}

    
    <ul class='list'>
        {% for libro in colección %}
            <li>{{libro}}
                <span>
                    <a href="{% url "colección:detallar" id=libro.id%}" class='btn btn-ops-v'>
                        <img src="{% static 'img/ver.png' %}" width=25px height=25px alt="Ver">
                    </a>
                    <a href="{% url "colección:editar" id=libro.id %}" class='btn btn-ops'>
                        <img src="{% static 'img/editar(2).png' %}" width=25px  alt="Editar">
                    </a>
                    <a href="{% url "colección:borrar" id=libro.id %}" class='btn btn-ops'>
                        <img src="{% static 'img/eliminar-simbolo.png' %}" width=25px  alt="Borrar">
                    </a>
                </span>
            </li>
        {% endfor %}
    </ul>

    
{% endblock 'content' %}