La_Cripta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name='inicio'),
    path('colección/', include('colección.urls')),
    path('usuarios/', include('usuarios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from . import views 

app_name = 'usuarios'
urlpatterns = [
    path('', views.listar, name='listar'),
    path('<letra>', views.listar, name='listar'),
    path('crear/', views.crear, name='crear'),
    path('detallar/<int:id>', views.detallar, name='detallar'),
    path('buscar_libros/', views.buscar_libros, name='buscar_libros'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('confirmacion-borrar/<int:id>', views.confirmacionBorrar, name='confirmacion-borrar'),
    path('borrar/<int:id>', views.borrar, name='borrar'),
    path('borrarYDevolverLibro/<int:id>', views.borrarYDevolverLibro, name='borrarYDevolverLibro'), #
    path('devolver/<int:id>', views.devolver, name='devolver'),

]

usuarios/models.py
from django.db import models
from colección.models import Colección
from django.utils import timezone

class Usuarios(models.Model):
    nombre = models.CharField(max_length=100, blank=False, null=False)
    apellido = models.CharField(max_length=100, blank=False, null=False)
    mail = models.EmailField(blank=False, null=False)
    tel = models.CharField(max_length=50, blank=False, null=False)
    direccion = models.CharField(max_length=100, blank=True, null=True)
    localidad = models.CharField(max_length=100, blank=False, null=False)
    fecha_de_registro= models.DateField(default=timezone.now)
    historial_de_prestamos = models.ManyToManyField('Prestamos', blank=True)
    adeuda = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.nombre} {self.apellido}'
    

class Prestamos(models.Model):
    usuario = models.ForeignKey(Usuarios, on_delete= models.CASCADE)
    libros = models.ManyToManyField(Colección, related_name='prestamos')
    fecha_de_prestamo = models.DateField(default = timezone.now)
    fecha_de_devolucion = models.DateField(blank=False, null=False)
    devuelto = models.BooleanField(default=False)
    
    def __str__(self):
        libros_str = ', '.join(libro.titulo for libro in self.libros.all())
        return f'{self.usuario} - Libros: {libros_str} - {self.fecha_de_prestamo}'

        












    
    

usuarios/forms.py
from django import forms
from django.forms import ModelForm
from .models import Usuarios, Prestamos, Colección


class Usuario_Form(ModelForm):
    class Meta:
        model = Usuarios
        exclude = ('fecha_de_registro','historial_de_prestamos',)
        widgets = {
            'adeuda': forms.HiddenInput(),
        }


class Prestamos_Form(ModelForm):
    class Meta:
        model = Prestamos
        exclude = ('fecha_de_prestamo',)
        widgets = {
            'fecha_de_devolucion': forms.DateInput(attrs={'type': 'date'}),
            'usuario': forms.HiddenInput(),
            'devuelto': forms.HiddenInput(),
        }

    libros = forms.ModelMultipleChoiceField(
        queryset=Colección.objects.filter(disponible=True),
        widget=forms.SelectMultiple(attrs={
            'data-searchable': 'true',
            'data-ajax--url': '/usuarios/buscar_libros/',
        })
    )

    

usuarios/views.py
from django.db import transaction
from django import forms
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, JsonResponse

from colección.forms import Colección_form
from .models import Usuarios, Prestamos, Colección
from .forms import Usuario_Form, Prestamos_Form
from django.contrib import messages

def listar(request, letra = None):
    if letra != None:
        usuarios = Usuarios.objects.filter(nombre__istartswith = letra)
    else:
        usuarios = Usuarios.objects.filter(nombre__contains = request.GET.get('search', ''))

    contexto = {
        'usuarios' : usuarios
    }

    return render(request, 'usuarios/view.html', contexto)


def crear(request):
    if request.method == 'POST':
        form = Usuario_Form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('usuarios:listar')
    else:
        form = Usuario_Form()
    
    contexto = {
        'form' : form
    }

    return render(request, 'usuarios/create.html', contexto)


def editar(request, id):
    usuario = Usuarios.objects.get(id=id)
    if request.method == 'POST':
        form = Usuario_Form(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            #messages.success(request, "Informacion actualizada.")
            return redirect('usuarios:listar')
    else:
        form = Usuario_Form(instance=usuario)

    contexto = {
        'form': form,
        'id':id
    }
    return render(request, 'usuarios/edit.html', contexto)
    

def confirmacionBorrar(request, id):
    usuario = Usuarios.objects.get(id=id)
    contexto = {
        'usuario':usuario
    }
    return render(request, 'usuarios/delete_confirm.html', contexto)


def borrar(request, id):
    usuario = Usuarios.objects.get(id=id)
    usuario.delete()
    return redirect('usuarios:listar')


def borrarYDevolverLibro(req, id):
    usuario = get_object_or_404(Usuarios, id=id)
    #devolver los libros prestados al usuario por borrar:
    prestamos = Prestamos.objects.filter(usuario=usuario , devuelto=False)

    with transaction.atomic():
        for prestamo in prestamos:
            for libro in prestamo.libros.all():
                libro.disponible = True
                libro.save()

        usuario.delete()


    return redirect('usuarios:listar')



def buscar_libros(request):
    term = request.GET.get('term', '')
    libros = Colección.objects.filter(titulo__icontains=term, disponible=True)
    results = [{'id': libro.id, 'text': libro.titulo} for libro in libros]
    
    return JsonResponse({'results': results})


def detallar(request, id):
    usuario = Usuarios.objects.get(id = id)

    if request.method == 'POST':
        form = Prestamos_Form(request.POST)
        if form.is_valid():
            form.save()
            with transaction.atomic():
                #Obtengo los libros seleccionados y actualizo el campo 'disponible'
                libros_seleccionados = form.cleaned_data['libros']
                for libro in libros_seleccionados:
                    libro.disponible = False
                    libro.save()

                #modifica el campo adeuda de el usuario cuando se lleva un libro:
                usuario.adeuda = True
                usuario.save()

                return redirect('usuarios:detallar', id=usuario.id)
    else:
        form = Prestamos_Form(initial={'usuario': usuario})
        

    prestamos = Prestamos.objects.filter(usuario__id=id)
    
    contexto = {
        'usuario': usuario,
        'prestamos': prestamos,
        'form' : form,
        'id' : id
    }

    return render(request, 'usuarios/detail.html', contexto)



def devolver(req, id):
    prestamo = get_object_or_404(Prestamos, id=id)
    usuarioId = prestamo.usuario.id
    # Uso transaction.atomic() para asegurar operaciones atómicas
    with transaction.atomic():
        prestamo.devuelto = True
        prestamo.save()

        libros_devueltos = prestamo.libros.all()
        for libro in libros_devueltos:
            libro.disponible = True
            libro.save()
        
        #aca cuando el usuario devuelva todos los libros ya no va a apareser que adeuda
        otros_prestamos_pendientes = Prestamos.objects.filter(usuario=prestamo.usuario, devuelto=False).exists()
        usuario = Usuarios.objects.get(id=usuarioId)
        usuario.adeuda = otros_prestamos_pendientes
        usuario.save()
        
    
    return redirect('usuarios:detallar', id=usuarioId)

usuarios/templates/usuarios/create.html
{% extends "layout/base.html" %}

{% block 'title' %}Registrar un miembro{% endblock 'title' %}


{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock styles %}



{% block 'content' %}

    {% load crispy_forms_tags %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="alert-success"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}


    <form action="{% url "usuarios:crear" %}" method='POST' novalidate >
        {% csrf_token %}

        {{ form | crispy }}

        <div class = 'd-grid gap-2'>
            <input type="submit" value='Guardar' class= 'btn btn-success'>
            <input type="reset" value='Limpiar' class= 'btn btn-secondary'>
        </div>
    </form>
{% endblock 'content' %}

usuarios/templates/usuarios/delete_confirm.html
{% extends "layout/base.html" %}

{% block 'title' %}Confirmar eliminación{% endblock 'title' %}

{% block 'content' %}

    <div class="card">
        <h5 class="card-header text-center">Confirmar eliminación</h5>
        <div class="card-body">
          <h5 class="card-title text-center">¿Estás seguro de que deseas eliminar a {{usuario.nombre}} {{usuario.apellido}}?</h5>
          
          {% if usuario.adeuda %}
            <p class="card-text text-center">Este usuario registra una o mas devoluciones pendientes,<br> puede hacer las devoluciones correspondientes<br> antes de eliminar el registro de lo contrario no se registrara<br> que los libros vuelvan a estar disponibles en la biblioteca.</p>
            
            <div class= 'd-flex justify-content-center'>
                <form method="post" action="{% url 'usuarios:borrarYDevolverLibro' id=usuario.id %}">
                    {% csrf_token %}
                    <button class="btn btn-warning mx-2 my-3" type="submit">Devolver y eliminar</button>
                </form>
                
                <form method="post" action="{% url 'usuarios:borrar' id=usuario.id %}">
                    {% csrf_token %}
                    <button class="btn btn-warning mx-2 my-3" type="submit">Si, eliminar</button>
                </form>

                <a class="btn btn-warning mx-2 my-3" href="{% url 'usuarios:listar' %}">Cancelar</a>
            </div>
          {% else %}
            <div class='d-flex justify-content-center'>
                <form method="post" action="{% url 'usuarios:borrar' id=usuario.id %}">
                    {% csrf_token %}
                    <button class="btn btn-warning mx-2 my-3" type="submit">Sí, eliminar</button>
                </form>
                <a class="btn btn-warning mx-2 my-3" href="{% url 'usuarios:listar' %}">Cancelar</a>
            </div>
            
          {% endif %}    
        </div>
      </div>


{% endblock 'content' %}

usuarios/templates/usuarios/detail.html
{% extends "layout/base.html" %}

{% block 'title' %}Libro: nombre del libro{% endblock 'title' %}


{% block 'content' %}
    {% load crispy_forms_tags %}

    <div class="container my-3" >
        <div class="row">
            <div class="col-sm-12 col-md-4 col-lg-4 col-xl-4">
                <!--Aca empiezan los datos del usuario-->
                <div class="card">
                    <h5 class="card-header"><center>{{usuario.nombre}}, {{usuario.apellido}}</center></h5>
                    <div class="card-body">
                      <p class="card-text"><b>Email:&nbsp;</b> {{usuario.mail}}</p>
                      <p class="card-text"><b>Telefono:&nbsp;</b> {{usuario.tel}}</p>
                      <p class="card-text"><b>Localidad:&nbsp;</b> {{usuario.localidad}}</p>
                      <p class="card-text"><b>Dirección:&nbsp;</b> {{usuario.direccion}}</p>
                      <p class="card-text"><b>Registrado:&nbsp;</b> {{usuario.fecha_de_registro}}</p>
                    </div>
                </div>

                <!--Aca empieza el formulario-->
                
                <form class='my-4' action="{% url "usuarios:detallar" id=id %}" method='POST' novalidate >
                    <h4>Registrar un prestamo</h4>
                    {% csrf_token %}
                    
                    {{ form | crispy }}

                    <div class = 'd-grid gap-2'>
                        <input type="submit" value='Guardar' class= 'btn btn-success'>
                        <input type="reset" value='Limpiar' class= 'btn btn-secondary'>
                    </div>
                </form>
            </div>
            
            <div class="col-sm-12 col-md-8 col-lg-8 col-xl-8">
                <!--Aca empieza el historial de prestamos-->
                <h2>Historial de prestamos</h2>
                <table class="table table-striped">
                    <thead class="table-light">
                      <tr>
                        <th scope="col">Fecha</th>
                        <th scope="col">Libros prestados</th>
                        <th scope="col">Fecha de devolución</th>
                        <th scope="col">Devolución</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for prestamo in prestamos reversed %}
                            <tr>
                                <td>{{prestamo.fecha_de_prestamo}}</td>
                                <td>
                                    {% for libro in prestamo.libros.all %}
                                    {{ libro.titulo }}{% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </td>
                                <td>{{prestamo.fecha_de_devolucion}}</td>
                                <td>
                                    {% if prestamo.devuelto %}Realizada{% else %} <a class="btn btn-primary" href="{% url "usuarios:devolver" id=prestamo.id %}">Devolver</a>  {% endif %}
                                </td>
                            </tr>
                        {% endfor %}  
                    </tbody>
                  </table>
            </div>
        </div>
    </div>

    
    
{% endblock 'content' %}

usuarios/templates/usuarios/edit.html
{% extends "layout/base.html" %}

{% block 'title' %}Editar libro{% endblock 'title' %}


{% block styles %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock styles %}



{% block 'content' %}

    {% load crispy_forms_tags %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="alert-success"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}


    <form action="{% url "usuarios:editar" id=id %}" method='POST' novalidate>
        {% csrf_token %}
        
        {{ form | crispy }}
        
        <input type="submit" value='guardar' class= 'btn-guardar'>
    </form>
{% endblock 'content' %}

usuarios/templates/usuarios/view.html
{% extends "layout/base.html" %}

{% block 'title' %}Usuarios{% endblock 'title' %}

{% block 'content' %}
{% load static %}


    {% include "usuarios/partials/by_initial.html" %}


    <ul class='list'>
        {% for usuario in usuarios %}
            <li>{{usuario}}
                <span>
                    <a href="{% url "usuarios:detallar" id=usuario.id%}" class='btn btn-ops-v'>
                        <img src="{% static 'img/ver.png' %}" width=25px height=25px alt="Ver">
                    </a>
                    <a href="{% url "usuarios:editar" id=usuario.id %}" class='btn btn-ops'>
                        <img src="{% static 'img/editar(2).png' %}" width=25px  alt="Editar">
                    </a>
                    <a href="{% url "usuarios:confirmacion-borrar" id=usuario.id %}" class='btn btn-ops'>
                        <img src="{% static 'img/eliminar-simbolo.png' %}" width=25px  alt="Borrar">
                    </a>
                         
                </span>
            </li>
        {% endfor %}
    </ul>

    

{% endblock 'content' %}